### ISSUE TITLE
Support for repository topics APIs

### ISSUE THREAD

**Issue by pmonks** [clj-commons/tentacles#9]
It would be great if tentacles supported the repository "topics" APIs:

* [Get API](https://developer.github.com/v3/repos/#list-all-topics-for-a-repository)
* [Set API](https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository)

**Comment by jjl** [comment]
I agree, it would be nice. However...

This module is not currently maintained as none of us at irresponsible currently write clojure.

I'd be happy to give you a commit bit if you were interested in adding these features, since the original project doesn't seem likely to get updated (although there are a few things open against it that might be worth looking at).
